# configuration file /etc/nginx/conf.d/cloudian.basic.metrics.conf:
server {
  listen       8080;
  listen  [::]:8080;
  access_log    off;
  log_not_found off;

  include include.d/limits.monitor.conf;
  location = /basic_status {
    stub_status;
  }
}