# configuration file /etc/nginx/conf.d/cloudian.metrics.conf:
server {
  listen       9114;
  listen  [::]:9114;
  include include.d/limits.monitor.conf;
  location /metrics {
    content_by_lua_block {
      metric_connections:set(ngx.var.connections_active, {"active"})  
      metric_connections:set(ngx.var.connections_reading, {"reading"})
      metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      metric_connections:set(ngx.var.connections_writing, {"writing"})
      prometheus:collect()
    }
  }
}
