# configuration file /etc/nginx/conf.d/s3-hni.sds.vnpaycloud.vn.conf:
upstream hyperstore-cloudian-s3-hni {
        zone upstream_hyperstore-cloudian-s3-hni 128k;
        least_conn;
        server  10.16.58.21:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.22:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.23:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.24:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.25:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.26:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.27:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.28:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.29:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.30:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.31:443 max_fails=2 fail_timeout=5s;
        server  10.16.58.32:443 max_fails=2 fail_timeout=5s;
        ## This options must the last line
        keepalive 60;
        keepalive_timeout 45s;
        keepalive_requests 200;
}

server {
    listen 443 ssl;
    http2 on;
    server_name    s3-hni.sds.vnpaycloud.vn;
    ssl_certificate /etc/nginx/ssl/s3-hni.sds.vnpaycloud.vn.crt;
    ssl_certificate_key /etc/nginx/ssl/s3-hni.sds.vnpaycloud.vn.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

    location / { 
        include /etc/nginx/include.d/proxy_options_s3.conf;

        access_by_lua_file /etc/nginx/libraries/customize/sites-additional-config/hyperstore-s3.lua;

        proxy_pass https://hyperstore-cloudian-s3-hni;
 
    }
}
