# configuration file /etc/nginx/include.d/proxy_options_s3_smaimages2.conf:
# Increase max body size
client_max_body_size 5g;
## Disable buffering requests & reponses
proxy_request_buffering off;
proxy_buffering off;
proxy_max_temp_file_size 0;

## Increae timeout for long-time connections
proxy_connect_timeout 10s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;

## Enable more header from proxy layer
#proxy_set_header Host $http_host;
proxy_set_header Host s3-hcm.sds.vnpaycloud.vn;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Cluster-Client-Ip $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;

# Default is HTTP/1, keepalive is only enabled in HTTP/1.1
proxy_http_version 1.1;
proxy_set_header Connection "";
# chunked_transfer_encoding off;

## disable gzip funxtion because backend highload traffic
gzip off;