# configuration file /etc/nginx/conf.d/vcr.vnpaycloud.vn.conf:
# Chỉ bật limit khi đúng domain
map $host $is_vcr {
    default 0;
    vcr.vnpaycloud.vn  1;
}

# ----- Key cho /service/token -----
# Lưu ý: KHÔNG gán giá trị mặc định; nếu thiếu account/scope thì phần đó rỗng.
map "$is_vcr|$uri|$arg_account|$arg_scope" $limit_key_token {
    default "";
    "~^1\|/service/token\|" "$binary_remote_addr$uri|a=$arg_account|s=$arg_scope";
}

limit_req_zone $binary_remote_addr zone=vcr_allapis:100m rate=2000r/s;
# /service/token
limit_req_zone $limit_key_token      zone=vcr_authapis:100m         rate=100r/s;


upstream vcr-kubernetes {
  server "10.2.67.193:443";
}

server {
  listen 443 ssl;
  http2 on;
  server_name vcr.vnpaycloud.vn;
  ssl_certificate /etc/nginx/ssl/vnpaycloud.vn.crt;
  ssl_certificate_key /etc/nginx/ssl/vnpaycloud.vn.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  client_max_body_size 0;

  # Add extra headers
  # add_header X-Frame-Options DENY;
  # add_header Content-Security-Policy "frame-ancestors 'none'";
  #limit_req zone=vcr_allapis burst=1000;
  #limit_req_status 429;
  #limit_req_log_level warn;

  location / {
    return 404;
  }

  location /v2/ {
    limit_req zone=vcr_allapis burst=1000;
    limit_req_status 429;
    limit_req_log_level warn;
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript application/x-yaml text/x-yaml;

    proxy_pass https://vcr-kubernetes/v2/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_send_timeout 900;
    proxy_read_timeout 900;
  }

  location /service/ {
    limit_req zone=vcr_authapis burst=100;
    limit_req_status 429;
    limit_req_log_level warn;
    proxy_pass https://vcr-kubernetes/service/;
    include /etc/nginx/include.d/proxy_options_default.conf;

    proxy_buffering off;
    proxy_request_buffering off;
  }

}