# configuration file /etc/nginx/conf.d/cmc.sds.vnpaycloud.vn.conf:
upstream hyperstore-cloudian-cmc {
        #ip_hash;
        hash "$http_x_forwarded_for";
        server  10.2.58.21:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.22:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.23:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.24:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.25:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.26:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.27:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.28:8443 max_fails=2 fail_timeout=5s;
        server  10.2.58.29:8443 max_fails=2 fail_timeout=5s;
}

server {
    listen 443 ssl;
    http2 on;
    server_name cmc.sds.vnpaycloud.vn sds.vnpaycloud.vn console.vnpaycloud.vn;
    ssl_certificate /etc/nginx/ssl/sds.vnpaycloud.vn.crt;
    ssl_certificate_key /etc/nginx/ssl/sds.vnpaycloud.vn.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /bucket_error.html {
        root /etc/nginx/html;
    }

    location / { 
        #Allow only access from Portal proxy
        allow 10.4.1.97/32;
        allow 10.2.17.0/24;
        deny all;

        include /etc/nginx/include.d/proxy_options_s3.conf;
        access_by_lua_file /etc/nginx/libraries/customize/sites-additional-config/cmc-conf.lua;
        proxy_cookie_flags JSESSIONID nohttponly;
        proxy_pass https://hyperstore-cloudian-cmc;
 
    }
}

server {
    listen 8443 ssl;
    http2 on;
    server_name cmc.sds.vnpaycloud.vn;
    ssl_certificate /etc/nginx/ssl/sds.vnpaycloud.vn.crt;
    ssl_certificate_key /etc/nginx/ssl/sds.vnpaycloud.vn.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / { 
        include /etc/nginx/include.d/proxy_options_s3.conf;
        proxy_pass https://hyperstore-cloudian-cmc;
 
    }
}
