# configuration file /etc/nginx/conf.d/hyperiq.sds.infiniband.vn.conf:
upstream hyperstore-cloudian-hyperiq {
        server 172.26.29.153:3000 max_fails=2 fail_timeout=10;
}

server {
    listen 443 ssl;
    http2 on;
    server_name hyperiq.sds.infiniband.vn;
    ssl_certificate /etc/nginx/ssl/sds.infiniband.vn.cert;
    ssl_certificate_key /etc/nginx/ssl/sds.infiniband.vn.key;

    location / {
        include /etc/nginx/include.d/proxy_options_default.conf;
        proxy_pass http://hyperstore-cloudian-hyperiq;

    }
}