# configuration file /etc/nginx/conf.d/s3-hni.sds.infiniband.vn.conf:
upstream hyperstore-cloudian-s3-hni {
        zone upstream_hyperstore-cloudian-s3-hni 128k;          # thêm
        least_conn;                                             # thêm
        server 172.25.171.24:443 max_fails=2 fail_timeout=5s;   # fail_timeout 10 → 5s
        server 172.25.171.25:443 max_fails=2 fail_timeout=5s;   # fail_timeout 10 → 5s
        server 172.25.171.26:443 max_fails=2 fail_timeout=5s;   # fail_timeout 10 → 5s
        ## This options must the last line
        keepalive 60;
        keepalive_timeout 45s;                                  # thêm
        keepalive_requests 200;                                 # thêm
}

server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name    s3-hni.sds.infiniband.vn;
    ssl_certificate /etc/nginx/ssl/sds.infiniband.vn.cert;
    ssl_certificate_key /etc/nginx/ssl/sds.infiniband.vn.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        include /etc/nginx/include.d/proxy_options_s3.conf;

        access_by_lua_file /etc/nginx/libraries/customize/sites-additional-config/hyperstore-s3.lua;

        proxy_pass https://hyperstore-cloudian-s3-hni;

    }
}
