worker_processes auto;

events {
    worker_connections 4096;
}

http {
    upstream apisix_pool {
        server apisix-dc1-1:9080;
        server apisix-dc1-2:9080;  # uncomment khi scale-out
    }

    server {
        listen 80;

        location / {
            proxy_pass http://apisix_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
}