# configuration file /etc/nginx/conf.d/minio.sds.infiniband.vn.conf:
upstream minio {
        server 172.26.29.185:9000 max_fails=2 fail_timeout=10;
        server 172.26.29.158:9000 max_fails=2 fail_timeout=10;
        server 172.26.29.170:9000 max_fails=2 fail_timeout=10;
        server 172.26.29.175:9000 max_fails=2 fail_timeout=10;
}

server {
    listen 443 ssl;
    http2 on;
    server_name minio.sds.infiniband.vn;
    ssl_certificate /etc/nginx/ssl/sds.infiniband.vn.cert;
    ssl_certificate_key /etc/nginx/ssl/sds.infiniband.vn.key;

    location / {
        include /etc/nginx/include.d/proxy_options_default.conf;
        proxy_pass http://minio;
    }
}