# configuration file /etc/nginx/conf.d/s3-admin.sds.infiniband.vn.conf:
upstream hyperstore-cloudian-admin {
        ip_hash;
        server 172.26.29.231:19443 max_fails=2 fail_timeout=10;
        server 172.26.29.232:19443 max_fails=2 fail_timeout=10;
        server 172.26.29.233:19443 max_fails=2 fail_timeout=10;
}

server {
    listen 443 ssl;
    listen 19443 ssl;
    http2 on;
    server_name s3-admin.sds.infiniband.vn;
    ssl_certificate /etc/nginx/ssl/sds.infiniband.vn.cert;
    ssl_certificate_key /etc/nginx/ssl/sds.infiniband.vn.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        include /etc/nginx/include.d/proxy_options_default.conf;
        proxy_pass https://hyperstore-cloudian-admin;

    }
}