plugin_configs:
  - id: "plugin-config-qos-internal-console"
    plugins:

      # kafka-logger:
      #   brokers:
      #     - host: "172.26.24.80"
      #       port: 31421
      #       sasl_config:
      #         mechanism: "SCRAM-SHA-512"
      #         user: "${{KAFKA_SASL_USER}}"
      #         password: "${{KAFKA_SASL_PASSWORD}}"
      #     - host: "172.26.24.80"
      #       port: 30215
      #       sasl_config:
      #         mechanism: "SCRAM-SHA-512"
      #         user: "${{KAFKA_SASL_USER}}"
      #         password: "${{KAFKA_SASL_PASSWORD}}"
      #     - host: "172.26.24.80"
      #       port: 30412
      #       sasl_config:
      #         mechanism: "SCRAM-SHA-512"
      #         user: "${{KAFKA_SASL_USER}}"
      #         password: "${{KAFKA_SASL_PASSWORD}}"

      #   kafka_topic: "apisix-gateway-${{DC_PROFILE}}"
      #   producer_type: async 
      #   batch_max_size: 1 
      #   timeout: 3
      #   # key: "$remote_addr"
      #   ssl: true
      #   ssl_verify: false
      #   meta_format: default
      #   api_version: 2

      limit-conn:
        conn: 4500
        burst: 500
        default_conn_delay: 0.1
        key_type: var
        key: remote_addr
        rejected_code: 429
        rejected_msg: "[APISIX-QOS:qos-internal-console]: Too many concurrent connections to internal console. Not a Cloudian error — check for stuck job/script."

      # ip-restriction:
      #   blacklist: []
      #   message: "Your IP has been temporarily blocked from internal console — contact platform team"

      request-id:
        header_name: "X-Request-Id"
        include_in_response: true

      response-rewrite:
        headers:
          set:
            X-RateLimit-Layer: "2"
