# configuration file /etc/nginx/conf.d/cloudian.metrics.conf:
server {
  listen       9114;
  listen  [::]:9114;
  access_log    off;
  log_not_found off;

  include include.d/limits.monitor.conf;
  location /metrics {
    content_by_lua_block {
      metric_connections:set(ngx.var.connections_active, {"active"})
      metric_connections:set(ngx.var.connections_reading, {"reading"})
      metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      metric_connections:set(ngx.var.connections_writing, {"writing"})
      prometheus:collect()
    }
  }
  # status page for all the peers:
  location = /healthcheck/status {
      access_log off;
      allow 172.0.0.0/8;
      allow 10.0.0.0/8;
      allow 192.168.0.0/16;
      deny all;

      default_type text/plain;
      content_by_lua_block {
          local hc = require "resty.upstream.healthcheck"
          ngx.say("Nginx Worker PID: ", ngx.worker.pid())
          ngx.print(hc.status_page())
      }
  }

	# status page for all the peers (prometheus format):
  location = /healthcheck/metrics {
      access_log off;
      default_type text/plain;
      content_by_lua_block {
          local hc = require "resty.upstream.healthcheck"
          local st , err = hc.prometheus_status_page()
          if not st then
              ngx.say(err)
              return
          end
          ngx.print(st)
      }
  }
}