# configuration file /etc/nginx/conf.d/s3-rgwhni-admin.sds.infiniband.vn.conf:
upstream ceph-rgwhni-admin {
        server 172.25.158.49:8443 max_fails=2 fail_timeout=10;
}upstream ceph-rgwhni-grafana {
        server 172.25.158.49:3000 max_fails=2 fail_timeout=10;
}
server {
    listen 443 ssl;
    http2 on;
    server_name s3-rgwhni-admin.sds.infiniband.vn;
    ssl_certificate /etc/nginx/ssl/sds.infiniband.vn.cert;
    ssl_certificate_key /etc/nginx/ssl/sds.infiniband.vn.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        include /etc/nginx/include.d/proxy_options_s3.conf;
        proxy_pass https://ceph-rgwhni-admin;

    }
    # Điều hướng /d về grafana
    location /d {
        proxy_pass http://ceph-rgwhni-grafana;
    }
    # Điều hướng /admin về ceph-rgwhni
    location /admin {
        include /etc/nginx/include.d/proxy_options_s3.conf;
        proxy_pass https://ceph-rgwhni;
    }
}