# configuration file /etc/nginx/conf.d/sqs.sds.infiniband.vn.conf:
upstream hyperstore-cloudian-sqs {
        ip_hash;
        server 172.26.29.231:18090 max_fails=2 fail_timeout=10;
        server 172.26.29.232:18090 max_fails=2 fail_timeout=10;
        server 172.26.29.233:18090 max_fails=2 fail_timeout=10;
        keepalive 12;
}

server {
    listen 80;
    http2 on;
    server_name sqs.sds.infiniband.vn;

    location / {
        include /etc/nginx/include.d/proxy_options_default.conf;
        proxy_pass http://hyperstore-cloudian-sqs;
    }
}